apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgquerynarrative.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | quote }}
  DATABASE_READONLY_PASSWORD: {{ .Values.secret.databaseReadonlyPassword | quote }}
